### ISSUE TITLE
Tensorflow Support

### ISSUE THREAD

**Issue by shivtotemic** [CalculatedContent/WeightWatcher#1]
Can we get a release for tensorflow?

**Comment by galenwilkerson** [comment]
I have to say, that would be great.

Or rather, perhaps possible to implement at the keras level, so is backend agnostic?  :-)

**Comment by charlesmartin14** [comment]
We have keras. Tf is much more complicated but we can do it if there is more support

**Comment by NikolasMarkou** [comment]
@charlesmartin14 any progress on this ?

**Comment by NikolasMarkou** [comment]
Ideally it should be the onnx format  not tensorflow, because onnx is becoming the standard
