### ISSUE TITLE
One potential problem of fitting alpha

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#103]
One potential problem I see with the fitting of alpha is that we always use the same powerlaw probabilistic density function (pdf) without considering the effect of xmax. Consider the following example.

![image (15)](https://user-images.githubusercontent.com/13740654/137417298-fd5dbd5a-68e0-438f-8f42-3d264e10ba38.png)

The pdf for a powerlaw distribution with xmin specified and a powerlaw distribution with both xmin and xmax specified are different. See the pdfs in the example above.

In the case that we specify xmax, the pdf is influenced by xmax, and thus the MLE needs to be changed (simply because the pdf is changed). If we keep using a pdf without xmax, that pdf is the wrong one, and thus the MLE gives a biased estimate.

I don't know if this is a bug or a feature. From theory, it seems that the fitting in weightwatcher clearly ignores the xmax in the pdf because it directly used the powerlaw package which uses the one without xmax. However, maybe this is something related to the particular use case of weightwatcher.

The one line of code in the powerlaw package that can be changed to address this problem is the following.
https://github.com/jeffalstott/powerlaw/blob/6732699d790edbe27c2790bf22c3ef7355d2b07e/powerlaw.py#L1188

Note that the powerlaw package does have one normalizer that takes into account the xmax issue. However, that one is not used in the current weightwatcher trunk.

**Comment by charlesmartin14** [comment]
There appears to be no resolution here.  Closing this issue for now.
