### ISSUE TITLE
Analyze fails on Conv1D layer 

### ISSUE THREAD

**Issue by manuel-delverme** [CalculatedContent/WeightWatcher#105]
`ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 18 is different from 1)
`

if it's relevant
![image](https://user-images.githubusercontent.com/1309922/146267185-8d2aaf00-4817-4152-9815-19b922e816e3.png)
this is the layer

**Comment by charlesmartin14** [comment]
That;s odd... Ill take a look thanks

**Comment by charlesmartin14** [comment]
Can you set up a google colab or similar notebook with a sample model ?

**Comment by charlesmartin14** [comment]
Sorry, i am unable to reproduce this. I;m happy to fix it if you can provide a model to test on
