### ISSUE TITLE
set_layer_id  not found

### ISSUE THREAD

**Issue by manuel-delverme** [CalculatedContent/WeightWatcher#106]
https://github.com/CalculatedContent/WeightWatcher/blob/0e71301d14431b6eaa12c159f70299607821f5e9/weightwatcher/weightwatcher.py#L1139

The dataframe has no attribute set_layer_id.

**Comment by charlesmartin14** [comment]
As with the other issue, can you share an example with the model ?

**Comment by charlesmartin14** [comment]
This should have been set_index
