### ISSUE TITLE
WeightWatcher.analyze() not working for wav2vec2

### ISSUE THREAD

**Issue by favrei** [CalculatedContent/WeightWatcher#128]
*Perhaps relate to https://github.com/CalculatedContent/WeightWatcher/issues/105

For testing purposes, I've fed the wav2vec2 model downloaded from huggingface to the weightwatcher.
It is stopped by an error very fast.

The code used is below:
```
import weightwatcher as ww
from transformers import AutoModelForCTC

model = AutoModelForCTC.from_pretrained("facebook/wav2vec2-base-960h")
watcher = ww.WeightWatcher(model=model)
details = watcher.analyze()
summary = watcher.get_summary(details)
```

It yields:
WARNING:weightwatcher:not enough eigenvalues, stopping
Traceback (most recent call last):
  File "t.py", line 6, in <module>
    details = watcher.analyze()
  File "/home/pete/.pyenv/versions/wristband/lib/python3.8/site-packages/weightwatcher/weightwatcher.py", line 1649, in analyze
    self.apply_analyze_eigenvectors(ww_layer, params=params)
  File "/home/pete/.pyenv/versions/wristband/lib/python3.8/site-packages/weightwatcher/weightwatcher.py", line 2931, in apply_analyze_eigenvectors
    X = np.matmul(W.T, W)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 512)

Versions:
torch==1.12.1+cpu
weightwatcher==0.5.6
transformers==4.22.1

Please let me know if you need additional information.

**Comment by charlesmartin14** [comment]
Try using the option 
#watcher.analyze(..., vectors=False, ..)
Thanks

**Comment by favrei** [comment]
After turning off the `vectors` the analyze function works.
Can you share more about the effect of the option? And under what circumstances should the option be disabled?
I've read the source code but still don't get the idea.
Thank You,

**Comment by favrei** [comment]
I meant I understand the `apply_analyze_eigenvectors` has been skipped when the option is disabled, but as far as I know, that is the point of this analysis, I don't get why would they be disabled.

**Comment by charlesmartin14** [comment]
The vector metrics are described in our JMLR paper
https://jmlr.org/papers/v22/20-410.html

They are not as informative as the power law metrics, but I have included them here, recently, for completeness.

Why is it broken?  I haven't figured that out yet but I suspect there is some layer that has only 1 eigenvalue and that somehow this slipped in and was analyzed by the method when it should not be...see the message below
`
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 512)`

You can test this by running
`details_df - watcher.describe()
`and checking the details dataframe to see if there are any layers with just 1 eigenvalue
I haven't had a chance to run this myself but I wil try to get to it shortly
I suggested just turning the option off so you can run the tool and get some useful metrics

**Comment by charlesmartin14** [comment]
BTW, here are the alphas..not so good at first glance
![Screen Shot 2022-09-26 at 10 04 06 PM](https://user-images.githubusercontent.com/498448/192436461-a6ebd8c3-2a8e-40d7-8947-44f4e659f091.png)

**Comment by favrei** [comment]
Can you also post the code how you generate the alpha plot?

**Comment by charlesmartin14** [comment]
```
details = watcher.analyze( min_evals=50)
details.alpha.plot.hist(bins=100)
plt.title("WeightWatcher Alpha for wav2vec2")
plt.xlabel(r"PL alpha $(\alpha)$")
```

**Comment by favrei** [comment]
Thank you, the snippet works.

Do you want to close the issue for now or wait for your patch?

Both work for me.

**Comment by charlesmartin14** [comment]
I want to look a little deeper into this as I was finding some bugs with min_evals = 10

**Comment by favrei** [comment]
ok, just let me know if you have any update. Thank you.

**Comment by charlesmartin14** [comment]
I have tried to reproduce this issue on the current trunk but can not

**Comment by charlesmartin14** [comment]
Im going to close this issue; please reopen if it comes up again
