### ISSUE TITLE
replace pandas.append()

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#137]
Pandas.append() is being deprecated; this needs to be replace

https://stackoverflow.com/questions/70837397/good-alternative-to-pandas-append-method-now-that-it-is-being-deprecated#:~:text=append%20was%20deprecated%20because%3A%20%22Series,'t%20be)%20in%20place.

Trying this:
If you want to use concat instead:

**append**
`outputxlsx = outputxlsx.append(df, ignore_index=True)
`

**concat**
`outputxlsx = pd.concat([outputxlsx, df])

**_Does not seem to work!_**
`

**Comment by charlesmartin14** [comment]
This can be checked using

`python tests/test.py Test_TFBert.test_num_layers
`

**Comment by charlesmartin14** [comment]
Also see:

L1757

`test_analyze_columns (tests.test.Test_VGG11)
`

**Comment by Alamwealthkid** [comment]
Thank you!!!!!!! so much!!!!

**Comment by charlesmartin14** [comment]
Thanks. Im trying to clean up all the warnings and get all the unit tests working

**Comment by charlesmartin14** [comment]
Unit tests pass on this on the trunk; closing the issue as this is being added to release 0.6.x

**Comment by cdhinrichs** [comment]
Whatever the solution turns out to be, just need to make sure that, if needed, `details.reset_index(drop=True)` is called at the end, so that the index is not all zeros.

**Comment by cdhinrichs** [comment]
It looks like the recommended change from the above has already been implemented - this is what's currently at the end of `watcher.analyze()`:
```python
                # issue 137
                # details = details.append(ww_layer.get_row(), ignore_index=True)
                data = pd.DataFrame.from_records(ww_layer.get_row() , index=[0])
                details = pd.concat([details,data])
```

**Comment by cdhinrichs** [comment]
The warning that currently shows up, and that was the origin of Issue #182 was this:
`WeightWatcher/weightwatcher/weightwatcher.py:2288: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.`

Issue #182 touches on the same line of code, and it involves deprecation of a pandas feature, but it's a different issue altogether.  This Issue looks to be already completed.

**Comment by charlesmartin14** [comment]
I assume we can close this now ?

**Comment by cdhinrichs** [comment]
Yes, this one was fixed a while back. Issue #182 was the more recent one, and it too can be closed.

**Comment by charlesmartin14** [comment]
closing
