### ISSUE TITLE
WeightWatcher 0.6.0 has been uploaded to TestPyPI

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#139]
WeightWatcher 0.6.0 has been uploaded to TestPyPI
https://test.pypi.org/project/weightwatcher/0.6.0/

You can install and test this using
python3 -m pip install --index-url https://test.pypi.org/simple/ weightwatcher

**Comment by Alamwealthkid** [comment]
Thank you for sharing

**Comment by Burhan-Q** [comment]
After making a new (clean) venv to install 0.6.0, ran into multiple dependency issues. Was able to resolve using (on Windows 10):

```PowerShell
python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple weightwatcher==0.6.0
```
