### ISSUE TITLE
Tests of Missing PyTorch Layers

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#14]
There are several PyTorch layers we don’t support yet.

https://pytorch.org/docs/stable/nn.html#

We would need to find implementations of pretrained models for them, such as

- Conv1D
- Conv3D
- ConvTranspose1d
- ConvTranspose3d

**Comment by thijsgelton** [comment]
Hi @charlesmartin14,

I am working with 3D operations operations and tried your library. I used the onnx example as well as the PyTorch example on the mainpage, but both of them didn't provide any summary or details output. It gave the following message: "WARNING:weightwatcher:No layers found". After inspecting the source code I found that they layers are not known to the library. Is there any status on whether these would be integrated any time soon? 

torchvision provides the S3D model with pretrained weights if you need any implementations.

PS: thank you for all your work. I can't wait to see the results on my models.

**Comment by charlesmartin14** [comment]
Yeah we don't support 3D layers
I guess it' doable but I don't have any experience with these models
Before we add such a feature Id like to learn more about them

**Comment by petteriTeikari** [comment]
Likewise, would be interested in having support for `Conv3D` operator as working with medical data here :) And thanks for the great work so far!
