### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by jordimas** [CalculatedContent/WeightWatcher#146]
macOS 11.6.4
Python 3.10.8
weightwatcher 0.5.7

After installing using  _pip3 install weightwatcher_

I get the exception:

_To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/jordi.mas/dev/models/weights.py", line 1, in <module>
    import weightwatcher as ww 
  File "/usr/local/lib/python3.10/site-packages/weightwatcher/__init__.py", line 29, in <module>
    from .weightwatcher import WeightWatcher
  File "/usr/local/lib/python3.10/site-packages/weightwatcher/weightwatcher.py", line 39, in <module>
    import sklearn
ModuleNotFoundError: No module named 'sklearn'_

In order to fix it, I had to install:

_pip3 install scikit-learn_

**Comment by charlesmartin14** [comment]
Oh ok I will confirm that we really need this and if so add it to the setup dependencies, thanks

**Comment by charlesmartin14** [comment]
ugh it appears that sklearn is being deprecated and replaced with scikit-learn
I will fix this in the next release

**Comment by charlesmartin14** [comment]
This should be fixed in the new release 0.6.1
