### ISSUE TITLE
Keras models taking GPU RAM

### ISSUE THREAD

**Issue by cdhinrichs** [CalculatedContent/WeightWatcher#184]
When I run tests locally I observe that > 10GB of GPU RAM is allocated, and is not freed for the duration of the testing process. I narrowed down the problem to this minimal case which, when run in a jupyter notebook, will allocate the same 10 GB without freeing it:

```python
from tensorflow.keras.applications.vgg16 import VGG16
model = VGG16()
del model
import gc
gc.collect()
```

after which, nvidia-smi reports:

```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1859746      C   python                           9157MiB |
```

The problem is that Keras is not freeing the GPU RAM, even after the model has been deleted from python memory. Prior to this, keras monopolizing GPU RAM was not an issue, however now that some operations require the GPU this is causing test failures due to CUDA being unable to allocate GPU RAM.

**Comment by cdhinrichs** [comment]
This appears to be the solution
https://stackoverflow.com/questions/52458244/keras-how-to-run-loaded-model-on-cpu

**Comment by charlesmartin14** [comment]
This appears to happen when weightwatcher accesses the layer weights

I think this might be fixed internally in weightwatcher by adding the following method to the `Modelterator`

first, create a stop_iteration_ method, that clears the keras session and then creates a new session

def stop_iteration_(self):
   if self.framework == FRAMEWORK.KERAS:
      tf.keras.backend.clear_session()
    session = tf.compat.v1.Session()

and then invoking this when the layer iteration finishes. i.e in 
    
 ```
   def next(self):
        curr_layer = next(self.layer_iter)
        if curr_layer:    
            return curr_layer
        else:
            self.stop_iteration_()
            raise StopIteration()
        
```
