### ISSUE TITLE
Divide by 0 warnings

### ISSUE THREAD

**Issue by cdhinrichs** [CalculatedContent/WeightWatcher#190]
Several tests produce a divide-by-zero warning,
```
WeightWatcher/weightwatcher/RMT_Util.py:139: RuntimeWarning: divide by zero encountered in divide
  return x, (1 / (2 * np.pi * sigma * sigma * x * y)) * np.sqrt((b - x) * (x - a))
```
which seems like it ought not to be. The following tests produce it:

Dive by 0 warnings:
`Test_VGG11.test_density_fit`                                   l 139 only
`Test_VGG11.test_mp_fit_columns`                         l 139 only
`Test_VGG11.test_randomize_mp_fits`                   l 139 only
`Test_VGG11.test_svd_sharpness2`                         l 139 only
`Test_VGG11.test_ww_softrank`                               l 139 only

Line 139 in RMU_Util.py is,
```python
def marchenko_pastur_pdf(x_min, x_max, Q, sigma=1.0, grid_size=0.001):
    """Return a discrete set of (x,y) values representing the Marchenko-Pastur distrbution from RMT.
    Computing on a grid of size 0.001 by default"""
    y = 1 / Q
    x = np.arange(x_min, x_max, grid_size)

    b = np.power(sigma * (1 + np.sqrt(1 / Q)), 2)  # Largest eigenvalue
    a = np.power(sigma * (1 - np.sqrt(1 / Q)), 2)  # Smallest eigenvalue
    
    return x, (1 / (2 * np.pi * sigma * sigma * x * y)) * np.sqrt((b - x) * (x - a))
```

Other tests (mostly the same group) produce a similar warning:
```
WeightWatcher/weightwatcher/RMT_Util.py:148: RuntimeWarning: invalid value encountered in sqrt
  return x, (1 / (np.pi * sigma * sigma)) * np.sqrt(4 - x ** 2)
```
This warning originates in either line 139 or line 148 of RMT_Util.py

Invalid sqrt value warnings:
`Test_VGG11.test_density_fit`                                  l 139 only
`Test_VGG11.test_mp_fit_columns`                        l 139 and 148
`Test_VGG11.test_rand_distance`                           l 148 only
`Test_VGG11.test_randomize`                                 l 148 only
`Test_VGG11.test_randomize_mp_fit`                    l 148 only
`Test_VGG11.test_runtime_warnings`                    l 148 only
`Test_VGG11.test_svd_sharpness`                           l 148 only
`Test_VGG11.test_svd_sharpness2`                         l 139 only
`Test_VGG11.test_svd_sharpness_with_model`     l 148 only
`Test_VGG11.test_ww_maxdist`                                l 148 only
`Test_VGG11.test_ww_softrank`                               l 139 only
`Test_VGG11.test_randomize_no_model`               l 148 only
`Test_VGG11.test_svd_sharpness_no_model`        l 148 only

Line 148 in RMT_Util.py is,
```python
def quarter_circle_pdf(x_min, x_max, sigma=1.0, grid_size=0.001):
    """Return a discrete set of (x,y) values representing the Quarter-Circle distribution from RMT.
    Computing on a grid of size 0.001 by default"""
    x = np.arange(x_min, x_max, grid_size)
    
    # When Q = 1, we look at the singular values instaed of eigenvalues
    return x, (1 / (np.pi * sigma * sigma)) * np.sqrt(4 - x ** 2)
```

**Comment by cdhinrichs** [comment]
Things that would cause the first (div by 0) error:
- sigma = 0
- x_min < 0  (Very unlikely)

Things that would cause the second (invalid value, i.e. less than 0):
- x_max > 2

**Comment by cdhinrichs** [comment]
The solution to the first error, div by 0, is that an xmin of 0 is indeed being passed. The solution is to swap this line,
`x = np.arange(x_min, x_max, grid_size)`
for this one
`x = np.arange(x_min+10**-9, x_max, grid_size)`
so that x no longer contains 0

**Comment by charlesmartin14** [comment]
I dont think that is the  core issue

I suspect that the MP fit method is failing because some of these matrices exhibit some form of rank collapse,
which causes the lower bound of the MP fit range (xmin) to extend  to zero, whereas it should be bounded above zero

I think the only time xmin would be zero is if Q = 1, and in this case the for should be performed using
the  Quarter Circle law , not the Marchenko Pastur law.

And I suspect this is throwing off the MP fits for these cases

Its not clear to me exactly how to fix this.
One approach might be to run randomize=True, and try to use that to estimate the lower bound of the MP fit
But if the randomized weight matrix has some form of rank collapse as well, then the problem will arise here also

If this is the case, I'm not sure how easy it will be to fix

**Comment by charlesmartin14** [comment]
see also: #163

**Comment by cdhinrichs** [comment]
First question: How was `marchenko_pastur_pdf` being called with an x_min argument of 0?

That function is invoked in only 2 places, both in RMT_Util.py. One is in `plot_density`, and the other is in `plot_density_and_fit`. In the latter, we have, at lines 253 - 258:
```python
   x_min, x_max = 0, np.max(bulk_fit)
    
    if Q == 1:
        x, mp = quarter_circle_pdf(x_min, x_max, sigma)
    else:
        x, mp = marchenko_pastur_pdf(x_min, x_max, Q, sigma)
```
Here we can see that `x_min` is being grounded to 0, causing the divide by 0 error.

In `plot_density`, we also have, at lines 280 - 283:
```python
    if method == "MP":
        to_plot = np.sort(to_plot)
        x_min, x_max = 0, np.max(to_plot)
        x, y = marchenko_pastur_pdf(x_min, x_max, Q, sigma)
```
Here again `x_min` is being set to 0. The suggestion above would work, or else revisiting what `x_min` should be in these 2 cases.

**Comment by cdhinrichs** [comment]
Next question: Why was `plot_density_and_fit` being called when `plot=False` was set in the call to `watcher.analyze`?

In `watcher.mp_fit`, the call to `plot_density` is behind an `if plot:` clause, but the call to `plot_density_and_fit` is outside of the following `if plot:` clause. It returns 3 values, `sigma_mp, x, mp = plot_density_and_fit(...`, and it looks like the first one, `sigma_mp` is returned from the function `mp_fit`. It would seem that `plot_density_and_fit` is being called unconditionally because it computes something that has to be returned.

However, if we trace the path taken by the `sigma_mp` that it returns, we can see the following:

First in `fit_mp` we have,
```python
        bw = 0.1 
        s1, f1 = fit_density_with_range(to_plot, Q, bw = bw)
        sigma_mp = s1
...
        sigma_mp, x, mp = plot_density_and_fit(model=None, ...
                              ..., Q=Q, num_spikes=0, sigma=s1,...)
```
Within `plot_density_and_fit` we have,
```
def plot_density_and_fit(..., sigma=None,...)
...
    if (sigma is None):
        evals = np.sort(eigenvalues)[::-1][num_spikes:]
        sigma = calc_sigma(Q, evals)
```

Two things are happening here
 - `s1` is first computed via `fit_density_with_range`, and a `sigma_mp = s1` variable is declared then silently overridden.
 - `s1` itself is passed as `sigma` to `plot_density_and_fit`, where, as `sigma` it will be re-calculated via a different path if and only if it is `None`.

It's also worth noting that `plot_density_and_fit` is only called in that one place in `weightwatcher.py`.  Also, note that in the call to `plot_density_and_fit`, `num_spikes=0`, and at any rate `num_spikes` does have a value calculated for it in `mp_fit`. Lastly, note that the other 2 return values of `plot_density_and_fit` are only needed if `plot` is true, and, that the call to `marchenko_pastur_pdf` is not needed in this case.

The recommendation is to move the calculation of `sigma_mp` out of `plot_density_and_fit`, and then move the call to `plot_density_and_fit` into the `if plot:` block.

**Comment by charlesmartin14** [comment]
The MP fits require fitting sigma
This is a bit tricky to get right in cases where the ESD is deformed far from MP

I think it would help to identify some of these cases and then review the fitting proceedure
to ensure that it gets the basic MP fits right, and then can handle these more difficult, even pathological , cases

**Comment by cdhinrichs** [comment]
The point I'm making about sigma is that you can make it so that sigma is computed exactly the way it was before, with no change for better or worse, but you can separate out the call to `plot_density_and_fit` and only call that if `plot=True`. 

This would kick the can down the road as to *how* exactly the mp fit is done, (by leaving it the same as it currently is,) while also getting rid of all of the warnings that are outputted by the tests.

**Comment by charlesmartin14** [comment]
Here's an example where the warning is issued, but the actual results look fine

![Screen Shot 2023-02-08 at 9 28 33 PM](https://user-images.githubusercontent.com/498448/217726470-79e0f069-3205-4075-894c-7fe049eba063.png)

It's unclear to me if this warning is material to the results of the fit or just cosmetic

**Comment by charlesmartin14** [comment]
With regard to this issue above:, in marchenko_pastur_pdf

it does appear that xmin=0 is probably the wrong setting unless Q=0
yes, I suspect a simple fix is in plot_density() where xmin should be > 0

def plot_density(to_plot, sigma, Q, method="MP", color='blue', cutoff=0.0):
```
    if method == "MP":
        to_plot = np.sort(to_plot)
         x_min, x_max = 0, np.max(to_plot)
        if Q > 1.0:
           x_min = (np.min(to_plot)+0.001)/2
      ...
```

**Comment by charlesmartin14** [comment]
After sleeping in this, several days, I think your original assessment is most likely correct and the MP fits need a separate issue

**Comment by charlesmartin14** [comment]
This does not fix the issue

**Here's the proposed fix**

```
def marchenko_pastur_pdf(x_min, x_max, Q, sigma=1.0, grid_size=0.001):
    """Return a discrete set of (x,y) values representing the Marchenko-Pastur distrbution from RMT.
    Computing on a grid of size 0.001 by default"""
    y = 1 / Q
    x = np.arange(x_min+10**-9, x_max, grid_size)

    b = np.power(sigma * (1 + np.sqrt(1 / Q)), 2)  # Largest eigenvalue
    a = np.power(sigma * (1 - np.sqrt(1 / Q)), 2)  # Smallest eigenvalu
    
LINE 140    return x, (1 / (2 * np.pi * sigma * sigma * x * y)) * np.sqrt((b - x) * (x - a)+10**-9)


def quarter_circle_pdf(x_min, x_max, sigma=1.0, grid_size=0.001):
    """Return a discrete set of (x,y) values representing the Quarter-Circle distribution from RMT.
    Computing on a grid of size 0.001 by default"""
    x = np.arange(x_min+10**-9, x_max, grid_size)
   
    # When Q = 1, we look at the singular values instead of eigenvalues
    return x, (1 / (np.pi * sigma * sigma)) * np.sqrt((4 - x ** 2)+10**-9)

```
**Here are the results**

`/Users/charleshmartin/anaconda3/envs/ww0.6.5/lib/python3.9/site-packages/weightwatcher-0.6.6.5-py3.9.egg/weightwatcher/RMT_Util.py:140: RuntimeWarning: invalid value encountered in sqrt`

**Comment by cdhinrichs** [comment]
The warnings have been addressed with the latest PR, though there may be some value in refactoring the mp_fit code so that at least `plot_density_and_fit` does not need to be called if plot is False.
