### ISSUE TITLE
add additional tests for the torchSVD

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#191]
Currently there is only 1 test for a the torchSVD, which is IMHO a major feature

`test_torch_svd`

and this test is a system test, it does not test the individual functions in RMTUtil but only the final outcome
Moreover, adding torchSVD broke several existing unit tests, and required turning down the tolerances at least one

I would feel more comfortable releasing this code with a larger set of tests which can help us maintain the code 

- tests of the new functionality added to RMTUtil without reference to the weightwatcher code that  calls the internal functions
- tests that can distinguish if torch is or is not running, so we can revert back the original tests for the numpy linalg functionality

ie. individual unit tests that can cover the variations  (including mistakes) on
```
test_eig_full(W, method=ACCURATE_SVD)
test_eig_full(W, method=FAST_SVD)
test_eig_full(W, method=BAD_METHOD)

test_svd_full(W, method=ACCURATE_SVD)
test_svd_full(W, method=FAST_SVD)
test_svd_full(W, method=BAD_METHOD)

test_svd_vals(W, method=ACCURATE_SVD):
test_svd_vals(W, method=FAST_SVD):
test_svd_vals(W, method=BAD_METHOD):

```

and some way to test the functionality when torch is not available

**Comment by cdhinrichs** [comment]
I've created a branch to add the following tests:
- Test that eig/svd_full/vals throws an AssertionError when a bad method is passed
- Test that if torch is available then `_eig/svd_full/vals_fast` is not `_eig/svd_full/vals_accurate`, and that those methods are the same when torch is unavailable
- Test that the torch _fast methods accurately reconstruct a 50x50 or 50x100 matrix to within given tolerances.

This branch is based on the pandas branch, so I can submit a PR when that one is accepted or rejected.
https://github.com/CalculatedContent/WeightWatcher/commit/a8b42672870895673e868713156e3dd289e312f3

**Comment by charlesmartin14** [comment]
Thanks
I was also hoping to have some other tests of the new functionality added to RMTUtil  `without reference to the weightwatcher classes  code `

Ill see if I can add these
