### ISSUE TITLE
Bugs in 0.6.4.3

### ISSUE THREAD

**Issue by cdhinrichs** [CalculatedContent/WeightWatcher#203]
I found a few bugs in the latest release, and I'll add any more here:

- Resolved ~~A variable `plot_id` is used instead of `layer_id` in formatting the layer name, which finds its way to the file name and plot title, a value of `-1` is being passed, leading to layer titles like `ww.layer-1.detX.png` and so on.~~
- In a past commit, part of PR #181 , two functions, `torch_load_sd` and `onnx_get_weights`, were moved to RMT_Util.py as part of a reworking of imports. This was later reverted, but the two functions weren't moved back into `weightwatcher.py`. 
- Resolved ~~Function `PyStateDictFileLayer.get_layer_iterator` has an unused `model` argument, but refers to an undefined `self`.~~
- Function `PyStateDictFileLayer.__init__` passes an undefined variable `layer` to its super constructor.
- Function `PyStateDictFileLayer.__init__` defines a variable `bias` inside of a conditional block if `layer_config['biasfile'] is defined, but if this is not the case then `bias` bay not be defined, yet `bias` is passed unconditionally to the super constructor.
- Resolved ~~In function `apply_detX`, `evals` is rescaled before computing `detX_val/num`, correctly. Then, evals is used in generating the `detX` plot, also correctly - in order to compare `detX_val` and `xmin` it is necessary for this rescaling to be done. However, before saving this value back to the dataframe, the eigenvalues are un-rescaled, meaning that the value saved into the dataframe can no longer be compared with xmin.~~

```python
def __init__(self, weights_dir, layer_config):
...
        if layer_config['biasfile']:
            biasfile = layer_config['biasfile']
            biasfile = os.path.join(weights_dir, biasfile)
            bias = np.load(biasfile) 
            biasfile = biasfile

    FrameworkLayer.__init__(self, layer, layer_id, name, longname=longname, weights=weights, bias=bias, the_type=the_type, framework=FRAMEWORK.PYSTATEDICT)
```

```python
evals = ww_layer.evals        
        evals, Wscale = rescale_eigenvalues(evals)
        detX_num, detX_idx = detX_constraint(evals, rescale=False)
        detX_val = evals[detX_idx]

        if plot:
            name = ww_layer.name
...
            plt.show(); plt.clf()
            
        evals = un_rescale_eigenvalues(evals, Wscale)
        detX_val = evals[detX_idx]
        ww_layer.add_column('detX_num', detX_num)  
        ww_layer.add_column('detX_val', detX_val)  
            
        return ww_layer
```

**Comment by charlesmartin14** [comment]
Thanks.  Some of the new unit tests failed as well 
Will try to finish debugging tonight

**Comment by charlesmartin14** [comment]
- PyStateDictFileLayer is not yet finished; this is not working yet

- PyStateDictLayer should mostly be working...still debugging

- on the detX scale, yes the un-rescaed was added to fic the issue comparing with xmin and mp_softrank
Is there another issue on this ?

**Comment by cdhinrichs** [comment]
I'm not aware of an issue that relates detX and mp_softrank in any way.

I do know that as of now if I try to compare detX_val and xmin I will get a wrong answer because detX_val in the details dataframe is un-rescaled. detX has to be rescaled in order to compare with xmin. The code for generating the plot uses the rescaled value, and the plot shows the right comparison. 

If there is a separate need for the un-rescaled detX_val, then perhaps the right thing to do is to set

```python
        detX_val_unrescaled = evals[detX_idx]
        ww_layer.add_column('detX_val_unrescaled', detX_val_unrescaled)  

        evals = un_rescale_eigenvalues(evals, Wscale)
        detX_val = evals[detX_idx]
        ww_layer.add_column('detX_num', detX_num)  
        ww_layer.add_column('detX_val', detX_val)  
```

**Comment by charlesmartin14** [comment]
Ok Il review this again before we release 0.7

**Comment by charlesmartin14** [comment]
See #164  (sorry this issue was not filled out properly)

**Comment by cdhinrichs** [comment]
The detX_val_unrescaled fix is in the latest PR.

**Comment by charlesmartin14** [comment]
Trying to close the issues with PyStateDictFileLayer

The current Test on the maser is partially working; but, the new test

Test_PyStateDictFileLayers

may leave some tmp cirectories in /tmp, named  /tmp/ww_...
working on clearning this up

**Comment by charlesmartin14** [comment]
I think all these issues have now been resolved, closing this
