### ISSUE TITLE
New pl_fit() plots do not include the theoretical PDF fit(dashed redline)

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#206]
here's what we have 

![image](https://user-images.githubusercontent.com/498448/221794721-5cd4e2a0-152e-4da2-b19e-07ffc7af9aa3.png)

2 differences:

- the data line (solid red) now extends to the left of the xmin vertical ine (ok)
- the theoretical fit (dashed line) is missing

What other plots look like
![image](https://user-images.githubusercontent.com/498448/221795977-969e02ba-fd38-42f9-a143-4acda23dc0f3.png)

**Comment by charlesmartin14** [comment]
Here's an example of where the plots fail and dont fail (VGG11)

to reproduce


`    
import weightwatcher as ww
import torchvision
import torchvision.models as models

vgg11 = models.vgg11(weights="IMAGENET1K_V1")
watcher = ww.WeightWatcher(vgg11)
details = watcher.analyze(plot=True, pool=False, conv2d_fft=True, vectors=False, min_evals=50)
`


![image](https://user-images.githubusercontent.com/498448/222590230-c8a3a080-5f9f-48b0-8e6e-a3dcf192377a.png)

![image](https://user-images.githubusercontent.com/498448/222590260-ae6c9afc-1534-4678-9bd4-deb35cbd87dc.png)

**Comment by cdhinrichs** [comment]
The latest PR fixes this issue.
