### ISSUE TITLE
Support on more Vision Models

### ISSUE THREAD

**Issue by CiaoHe** [CalculatedContent/WeightWatcher#272]
Awesome work! Besides, any future plans of integrating with more advanced vision models? Perhaps the analyzing of Stable Diffusion Models or other fantastic generative models' weights is urgently needed

**Comment by charlesmartin14** [comment]
Actually I been focussing mostly on LLMs

https://weightwatcher.ai/leaderboard.html

Can you suggest some specific stable diffusion models to look at ?

**Comment by CiaoHe** [comment]
cool. For example, stable diffusion v1.5 and stable diffusion v2.1 are two main popular versions. Here's some introduction: [SDv1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5); [SDv2.1](https://huggingface.co/stabilityai/stable-diffusion-2-1)
Some interesting visualization aspects include: 
* Different stages of UNet layers (Encoder, Middle, Decoder); 
* Self-attention layer & Cross-attention layer
* ...

**Comment by charlesmartin14** [comment]
UNet models a re bit hard to analyze because they condense down to a very rectangular layer at the bottom
Weightwatcher works better for large, square or nearly square matrices

**Comment by CiaoHe** [comment]
Yeah, I agree with it. Thanks for your reply.

**Comment by charlesmartin14** [comment]
sure thing
