### ISSUE TITLE
WW has problems with the Sequential module

### ISSUE THREAD

**Issue by pgniewko** [CalculatedContent/WeightWatcher#273]
I checked that if part of my model uses `Sequential` module that contains multiple `Linear` layers, these `Linear` layers are not included in statistics calculations.

For example, the MLP module I implemented, is not included in the WW analysis:
```
  (mlp): Sequential(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=128, out_features=128, bias=True)
  )
```

**Comment by charlesmartin14** [comment]
Gotcha.  Ill debug this, see whats going on...that is od

Can you provide the code used to generate this

**Comment by pgniewko** [comment]
I looked into this issue more, and I think the problem was on my end. I got confused by how `model.modules()` unrolls each module. Thanks!
