### ISSUE TITLE
MXNet Support

### ISSUE THREAD

**Issue by mitchellgordon95** [CalculatedContent/WeightWatcher#28]
Hello! I love this work, thanks for open-sourcing it.

My department is a heavy user of the [Sockeye](https://github.com/awslabs/sockeye) framework for seq2seq learning, which internally relies on [MXNet](https://mxnet.apache.org/) as opposed to PyTorch or TF.

I'd like to go back and run this tool on our models and am willing to put in some elbow grease to get MXNet support. I'm wondering if you have any idea of the steps involved in this, roughly, and the amount of work they would be. That would help me get started and decide if this project is worth the effort.

Thanks!

**Comment by charlesmartin14** [comment]
THat would be great if you could lend a hand.  You can join our slack channel to discuss further if you like

**Comment by charlesmartin14** [comment]
In the new version, 0.4, this should be possible.  It;'s very easy.  We simply need to extend the ModelIterator to support MxNet, and the WWLayer class to ensure it recognizes the LAYER_TYPE and the get_weights_and_biases() method

If there is still inteterst here, please reach out

**Comment by charlesmartin14** [comment]
I dont see MXNET support being added soon so closing this issue for now.  If there is a string demand I will revisit this
