### ISSUE TITLE
Any plans to support pytorch2.x?

### ISSUE THREAD

**Issue by davidjimenezphd** [CalculatedContent/WeightWatcher#298]
Just wondering whether there is any plan to support pytorch2.x and decouple torch-tensorflow dependencies.
Thanks!

**Comment by charlesmartin14** [comment]
we remove the explicit tensorflow dependencies sometime ago

The current versions should dynamically load the correct package  (pytorch or tensor flow) depending on the model, and or what you have available in your environment

I thought we supported pytorch 2.0 but I'm not sure I'll check.

**Comment by davidjimenezphd** [comment]
Tested and finally working. Apologies for raising the issue before testing it. I checked the requirements in the readme and raised the issue (I guess the requirements are outdated).
![image](https://github.com/CalculatedContent/WeightWatcher/assets/30496090/6188a5bd-c12f-4e26-afed-6fa0881f0a20)

Thanks for answering!
