### ISSUE TITLE
Error while plotting

### ISSUE THREAD

**Issue by sdpillay** [CalculatedContent/WeightWatcher#40]
After upgrading to 0.4.0 I see this error on the analyst method, This worked with 0.2.6 version

**My code**
    mdl1 = binaryClassification(input_size, BATCH_SIZE)
    #mdl.to(device)
    mdl1.load_state_dict(torch.load('my_model.mdl'))
    
    watcher = ww.WeightWatcher(model=mdl1)
    results1 = watcher.analyze(plot()
    plt.show()

**Error**
DEBUG:weightwatcher:fitting power law on 1 eigenvalues
Less than 2 unique data values left after xmin and xmax options! Cannot fit. Returning nans.
Traceback (most recent call last):
 File "/Users/sanjaypillay/MS_DS/git/maps_capstone/ww_v1_model.py", line 192, in nn_kmer
    results1 = watcher.analyze(plot=True)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/weightwatcher/weightwatcher.py", line 976, in analyze
    self.apply_fit_powerlaw(ww_layer, params)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/weightwatcher/weightwatcher.py", line 875, in apply_fit_powerlaw
    alpha, xmin, xmax, D, sigma, num_pl_spikes = self.fit_powerlaw(evals, xmin=xmin, xmax=xmax, plot=plot, title="", sample=sample, sample_size=sample_size)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/weightwatcher/weightwatcher.py", line 1305, in fit_powerlaw
    fig2 = fit.plot_pdf(color='b', linewidth=2)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/powerlaw.py", line 525, in plot_pdf
    return plot_pdf(data, ax=ax, linear_bins=linear_bins, **kwargs)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/powerlaw.py", line 2073, in plot_pdf
    edges, hist = pdf(data, linear_bins=linear_bins, **kwargs)

  File "/Users/sanjaypillay/anaconda3/envs/phy_r_37/lib/python3.7/site-packages/powerlaw.py", line 1950, in pdf
    xmax = max(data)

ValueError: max() arg is an empty sequence

**Comment by charlesmartin14** [comment]
Please try using the option ww2x=True and let me know if it works

Can you provide a model file so I can reproduce this ?

**Comment by sdpillay** [comment]
Pickle file attached
Code used to read pickle 
    mdl1 = binaryClassification(input_size, BATCH_SIZE)
    #mdl.to(device)
    mdl1.load_state_dict(torch.load('my_model.mdl'))
    
    watcher = ww.WeightWatcher(model=mdl1)
    results1 = watcher.analyze(plot=True,  ww2x=True)
    plt.show()
    print(results1)    
    summary_11 = watcher.get_summary()

[my_model.mdl.zip](https://github.com/CalculatedContent/WeightWatcher/files/5543334/my_model.mdl.zip)

**Comment by sdpillay** [comment]
ww2x=True option has the same error

**Comment by charlesmartin14** [comment]
OK il take a look in detail

**Comment by charlesmartin14** [comment]
I can't read this model file without the classes for the model. 

Please try setting min_evals=100 and rerunning  weightwatcher

**Comment by sdpillay** [comment]
When I run with this option, I get no plots. I am attaching my sample python code that will read the saved model and run WW analysis, it has the model file. hope it helps.

[ww_test_model.py.zip](https://github.com/CalculatedContent/WeightWatcher/files/5554851/ww_test_model.py.zip)

Empty DataFrame
Columns: [layer_id, name]
Index: []
{}

**Comment by charlesmartin14** [comment]
I think the bug is that there is a 2-D matrix of dimension (1x100), which the code can not detect
If you set min_evals=10, that should fix it
But I will check with this code

**Comment by charlesmartin14** [comment]
I have confirmed this works
Please let me know if you can also confirm this

**Comment by sdpillay** [comment]
looks like 10 worked initially I had set it to 100. Thank you I will run this on my actual model and see now.

**Comment by charlesmartin14** [comment]
Im going to leave the issue open until I fix the bug re-release
Thanks for pointing this out!
