### ISSUE TITLE
Math Warnings On Analyze

### ISSUE THREAD

**Issue by xanderdunn** [CalculatedContent/WeightWatcher#53]
I see a couple of warning messages when I run `analyze()`:
```
/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/powerlaw.py:700: RuntimeWarning: divide by zero encountered in true_divide
  (Theoretical_CDF * (1 - Theoretical_CDF))
/home/xander/anaconda3/envs/my_model/lib/python3.7/site-packages/powerlaw.py:700: RuntimeWarning: invalid value encountered in true_divide
  (Theoretical_CDF * (1 - Theoretical_CDF))
Less than 2 unique data values left after xmin and xmax options! Cannot fit. Returning nans.
```

These don't cause a crash or prevent getting results, but I wonder should I expect to see these messages / is it potentially a problem?

**Comment by charlesmartin14** [comment]
That's fine...that's the powerlaw solver..embedded code...I suppose I should supress these warnings

**Comment by xanderdunn** [comment]
Great, thanks.  Feel free to close. An easy alternative might just be mentioning in the README that the warnings are expected.

**Comment by charlesmartin14** [comment]
great suggestion thanks!
