### ISSUE TITLE
Graphs plotted in the same figure

### ISSUE THREAD

**Issue by Evap6** [CalculatedContent/WeightWatcher#57]
When i run _details = watcher.analyze(plot = True)_ all figures are plotted in the same figure. How can i handle it?

![Figure_1](https://user-images.githubusercontent.com/48203303/119155977-09d67180-ba54-11eb-94d7-69d0dfa10c30.png)

**Comment by charlesmartin14** [comment]
Sorry there appears to be a bug. I will try to reproduce it and fix it today.

**Comment by Evap6** [comment]
I'm actually running version 0.4.6. I installed it using pip on anaconda3.

![Screenshot_1](https://user-images.githubusercontent.com/48203303/119309063-13d3bc80-bc6e-11eb-8d39-4f08eb3c0b92.png)

I tried to uninstall and reinstall the package but it didn't work.

**Comment by Evap6** [comment]
I'm actually using version 0.4.6. I installed it using pip on anaconda3.

![Screenshot_1](https://user-images.githubusercontent.com/48203303/119309247-57c6c180-bc6e-11eb-9105-742233cd0fd5.png)

**Comment by charlesmartin14** [comment]
That is really odd
I will try to reproduce from a clean environment than

Maybe there is something wrong with the pypi distribution 
I can also re-release the package with a new minor release

**Comment by Evap6** [comment]
Thank you!

**Comment by charlesmartin14** [comment]
Please try the latest minor release, 0.4.7
