### ISSUE TITLE
Using average alpha as part of loss function?

### ISSUE THREAD

**Issue by federicoparra** [CalculatedContent/WeightWatcher#59]
I'm wondering in the context of regression, what would happen if one created a Loss function that includes alpha, for example by multiplying current MSE by alpha, so that as alpha decreases so does the loss?

**Comment by charlesmartin14** [comment]
My main goal now is to get the current code base stabilized for a 1.0 major release
I don't think we can implement a differentiable alpha by then

**Comment by charlesmartin14** [comment]
closing this issue
