### ISSUE TITLE
Issue of savefig

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#76]
When running the following python script, the figures saved overlap with each other.

```
import weightwatcher as ww
import torchvision.models as models

model = models.vgg19_bn(pretrained=True)
watcher = ww.WeightWatcher(model=model)
details = watcher.analyze(plot=True, savefig=True)
summary = watcher.get_summary(details)
```
Here is one figure. 
![ww layer2 esd4](https://user-images.githubusercontent.com/13740654/127590710-c6d0e124-be58-40b4-8ba1-a6fdd713906c.png)

It seems that changing `plt.show()` to `plt.clf()` can make the figures look normal again.

Also, it will be great if there is an option to specify the folder to save the figures. I think now the code saves the figure in the current directory. Thanks!

I am using python 3.8.8, tensforflow 2.4.1 and keras 2.4.0. The weightwatcher installed is 0.4.7.

**Comment by charlesmartin14** [comment]
This bug was fixed several weeks ago in the current Trunk but the code had to be reverted to fix another problem.

Please install version the latest testpypi the following:

python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple weightwatcher

I will be upgrading the main pypi site shortly

**Comment by charlesmartin14** [comment]
It appears this is only a bug when running ww from the command line, and not in a jupyter notebook

**Comment by charlesmartin14** [comment]
It has been suggested to replace plot.show() with plt.clf() so the plots can be exported

**Comment by federicoparra** [comment]
Not sure it's relevant but in Jupyter notebooks I've found overlapping plots when the iPython command %config InlineBackend.close_figures=False was executed. If %config InlineBackend.close_figures=True is set then the problem disappear. Might want to try that.

**Comment by nsfzyzz** [comment]
Thanks for addressing the problem. Yeah, I think replacing the plt.show() with plt.clf() solves the problem when running the code in a python script

**Comment by nsfzyzz** [comment]
By the way, I have tried to add plt.clf() after plt.show(), e.g., in the fit_powerlaw() function. 

https://github.com/CalculatedContent/WeightWatcher/blob/d6efa60feddcda18dec9ec055b4e1c9de2e1bc66/weightwatcher/weightwatcher.py#L1710
https://github.com/CalculatedContent/WeightWatcher/blob/d6efa60feddcda18dec9ec055b4e1c9de2e1bc66/weightwatcher/weightwatcher.py#L1721
https://github.com/CalculatedContent/WeightWatcher/blob/d6efa60feddcda18dec9ec055b4e1c9de2e1bc66/weightwatcher/weightwatcher.py#L1733
https://github.com/CalculatedContent/WeightWatcher/blob/d6efa60feddcda18dec9ec055b4e1c9de2e1bc66/weightwatcher/weightwatcher.py#L1747

That can remove the overlap when running the python script. Also, it does not change the plotting functions in jupyter notebook.

**Comment by charlesmartin14** [comment]
This has now been fixed in the trunk.
plt.clf() has been added after all plt.show() methods
