### ISSUE TITLE
Maybe typo in mp_fit?

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#78]
https://github.com/CalculatedContent/WeightWatcher/blob/76c8842da67447868760decb13c0f59989e403e4/weightwatcher/weightwatcher.py#L2058

Should the 'formt' be 'format'? There are a few places where this happens. It gives an error when trying to save the mp_fit figure in jupyter notebook.

**Comment by charlesmartin14** [comment]
This has been fixed in the trunk, thanks
