### ISSUE TITLE
Single-line plot in mp_fit

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#79]
Hi,

I got the following figure when using mp_fit=True and randomize=True. 

![image](https://user-images.githubusercontent.com/13740654/127781924-2853bbe3-06c3-40a0-b60c-af3881e6bba9.png)

Here is a Google colab notebook to reproduce the figure.
https://colab.research.google.com/drive/1GMm2Xz5yj6x-APIS2Cy6iwRTcYmus1tm?usp=sharing

**Comment by charlesmartin14** [comment]
This work better (but not completely correctly) when using `rescale=False`
This is the same as issue #60
