### ISSUE TITLE
Q should be always greater than 1.0

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#81]
The parameter Q can become smaller than 1.0 for some ResNet101 layers. This issue can cause the mp_fit feature to give inaccurate fitting. I think adding flipping N and M can solve the issue. Consider adding 
`if N < M:
    M, N = N, M`
to the following function. 
https://github.com/CalculatedContent/WeightWatcher/blob/b5f4081009d12795c983ad7da91caddeb4dd8af5/weightwatcher/weightwatcher.py#L2020

**Comment by charlesmartin14** [comment]
I think this will fix it...testing 

in conv2D_Wmats:
```
...
                        if W.shape[0] < W.shape[1]:
                            N, M = M, N.  #FIXED 
                            W = W.T
                        Wmats.append(W)
```

**Comment by charlesmartin14** [comment]
This is fixed in the Trunk
It should be tested with cases when say the channels are flipped explicity
