### ISSUE TITLE
Adding a savefolder feature

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#83]
It would be great if the code has a `savefolder` option to specify where the figures should be saved. Here is one example.

https://github.com/CalculatedContent/WeightWatcher/blob/e11d2beb0767bc11dbddefcf6b385426164304bd/weightwatcher/weightwatcher.py#L1678

I changed the code to the following. The savefolder option is `None` in the default case.

```
if savefig:
    file_name = "ww.layer{}.randesd.1.png".format(layer_id)
    if not params['savefolder']:
        plt.savefig(file_name)
    else:
        plt.savefig(os.path.join(params['savefolder'], file_name))
plt.show(); plt.clf()
```

**Comment by charlesmartin14** [comment]
This has been added to the trunk, please confirm it is working correctly

**Comment by charlesmartin14** [comment]
Implemented
