### ISSUE TITLE
Index out of bound issue for small matrix

### ISSUE THREAD

**Issue by nsfzyzz** [CalculatedContent/WeightWatcher#95]
The code here https://github.com/CalculatedContent/WeightWatcher/blob/f730ffa54d1d1d6c71c5db4a8a65f1869e5d628e/weightwatcher/weightwatcher.py#L2765 causes an index out of bound issue for a small matrix with M=2. You can change the code to the following, i.e., changing < to <=.

`xval = np.where(sorted_evals <= xmin)[0][-1]`

**Comment by nsfzyzz** [comment]
I think a more appropriate way is to automatically neglect layers that only have 2 eigenvalues.

**Comment by charlesmartin14** [comment]
this should work with

watcher.analyze(..., min_size=3, ...)

**Comment by charlesmartin14** [comment]
The 0.5.7 release will reset min_evals = 50 to prevent this
