### ISSUE TITLE
Lightning Flash Notebook example

### ISSUE THREAD

**Issue by SeanNaren** [CalculatedContent/WeightWatcher#96]
Been using WeightWatchers with some of the [Lightning Flash](https://github.com/PyTorchLightning/lightning-flash) tasks which has been awesome (supports LightningModules out the box!).

I've been working within a notebook and would be cool to contribute it back to the repo :) let me know if this is something you'd like @charlesmartin14!!

**Comment by charlesmartin14** [comment]
Glad to hear it.  The feedback is useful.  I'll check out the pull request.
